import {
  FaSolidArrowsLeftRight,
  FaSolidBox,
  FaSolidCalculator,
  FaSolidEquals,
  FaSolidGreaterThanEqual,
  FaSolidMagnifyingGlass,
  FaSolidSkullCrossbones,
  FaSolidToggleOn,
  FaSolidUpRightFromSquare,
  FaSolidCircleExclamation,
  FaSolidArrowRight,
  FaSolidArrowLeft,
  FaSolidQuoteLeft,
  FaSolidDownLeftAndUpRightToCenter,
  FaSolidSignsPost,
  FaSolidRuler,
  FaSolidCircleCheck,
  FaSolidTriangleExclamation,
  FaSolidGlobe,
  FaSolidListOl,
  FaSolidMattressPillow,
  FaSolidKeyboard,
  FaSolidStrikethrough,
  FaSolidHashtag,
  FaSolidShuffle,
  FaSolidArrowRightToBracket,
  FaSolidArrowRightFromBracket,
  FaSolidCommentDots,
} from "solid-icons/fa";

export const Icons_Dict = {
  list_length: FaSolidArrowsLeftRight,
  variable_extraction: FaSolidUpRightFromSquare,
  string_interpolation: FaSolidQuoteLeft,
  http_request: FaSolidGlobe,
  is_nan: FaSolidTriangleExclamation,
  truthiness: FaSolidCircleCheck,
  variable_remapping: FaSolidSignsPost,
  string_length: FaSolidRuler,
  string_concat: FaSolidDownLeftAndUpRightToCenter,
  list_head_separation: FaSolidArrowLeft,
  is_finite: FaSolidSkullCrossbones,
  list_tail_separation: FaSolidArrowRight,
  negation: FaSolidCircleExclamation,
  equals: FaSolidEquals,
  string_contains: FaSolidMagnifyingGlass,
  number_comparison: FaSolidGreaterThanEqual,
  math: FaSolidCalculator,
  boolean_operation: FaSolidToggleOn,
  optional_or_else: FaSolidBox,
  ["value_provider_Optional[number]"]: FaSolidListOl,
  ["value_provider_Optional[boolean]"]: FaSolidMattressPillow,
  ["value_provider_Optional[string]"]: FaSolidKeyboard,
  ["value_replacer_Optional[string]"]: FaSolidStrikethrough,
  ["value_replacer_Optional[number]"]: FaSolidHashtag,
  ["value_replacer_Optional[boolean]"]: FaSolidShuffle,
  webhook_start: FaSolidArrowRightToBracket,
  webhook_end: FaSolidArrowRightFromBracket,
  parse_string_to_number: FaSolidCommentDots,
};
