import {
  FaBrandsDiscord,
  FaSolidArrowDownAZ,
  FaSolidArrowLeft,
  FaSolidArrowRight,
  FaSolidArrowRightFromBracket,
  FaSolidArrowRightToBracket,
  FaSolidArrowsLeftRight,
  FaSolidArrowsSplitUpAndLeft,
  FaSolidArrowUpAZ,
  FaSolidBackward,
  FaSolidBarsStaggered,
  FaSolidBox,
  FaSolidBoxArchive,
  FaSolidBoxOpen,
  FaSolidCalculator,
  FaSolidCircleCheck,
  FaSolidCircleExclamation,
  FaSolidClone,
  FaSolidCode,
  FaSolidCommentDots,
  FaSolidDiagramSuccessor,
  FaSolidDownLeftAndUpRightToCenter,
  FaSolidEquals,
  FaSolidFile,
  FaSolidFileArrowDown,
  FaSolidFileCircleCheck,
  FaSolidFileCirclePlus,
  FaSolidFileCircleQuestion,
  FaSolidFileCircleXmark,
  FaSolidFileExcel,
  FaSolidGlobe,
  FaSolidGreaterThanEqual,
  FaSolidHashtag,
  FaSolidIndent,
  FaSolidKeyboard,
  FaSolidList,
  FaSolidListCheck,
  FaSolidListOl,
  FaSolidMagnifyingGlass,
  FaSolidMattressPillow,
  FaSolidObjectUngroup,
  FaSolidPersonDigging,
  FaSolidQuoteLeft,
  FaSolidRuler,
  FaSolidShuffle,
  FaSolidSignsPost,
  FaSolidSkullCrossbones,
  FaSolidStrikethrough,
  FaSolidTerminal,
  FaSolidToggleOff,
  FaSolidToggleOn,
  FaSolidTriangleExclamation,
  FaSolidTruckRampBox,
  FaSolidUpRightFromSquare,
  FaSolidWandMagicSparkles,
} from "solid-icons/fa";

export const Icons_Dict = {
    list_length: FaSolidArrowsLeftRight,
    variable_extraction: FaSolidUpRightFromSquare,
    string_interpolation: FaSolidQuoteLeft,
    http_request: FaSolidGlobe,
    is_nan: FaSolidTriangleExclamation,
    truthiness: FaSolidCircleCheck,
    variable_remapping: FaSolidSignsPost,
    string_length: FaSolidRuler,
    string_concat: FaSolidDownLeftAndUpRightToCenter,
    list_head_separation: FaSolidArrowLeft,
    is_finite: FaSolidSkullCrossbones,
    list_tail_separation: FaSolidArrowRight,
    negation: FaSolidCircleExclamation,
    equals: FaSolidEquals,
    string_contains: FaSolidMagnifyingGlass,
    number_comparison: FaSolidGreaterThanEqual,
    math: FaSolidCalculator,
    boolean_operation: FaSolidToggleOn,
    optional_or_else: FaSolidBox,
    ["value_provider_Optional[number]"]: FaSolidListOl,
    ["value_provider_Optional[boolean]"]: FaSolidMattressPillow,
    ["value_provider_Optional[string]"]: FaSolidKeyboard,
    ["value_replacer_Optional[string]"]: FaSolidStrikethrough,
    ["value_replacer_Optional[number]"]: FaSolidHashtag,
    ["value_replacer_Optional[boolean]"]: FaSolidShuffle,
    webhook_start: FaSolidArrowRightToBracket,
    webhook_end: FaSolidArrowRightFromBracket,
    parse_string_to_number: FaSolidCommentDots,
    object_set_value: FaSolidObjectUngroup,
    value_provider_number: FaSolidListOl,
    get_at_index: FaSolidIndent,
    value_provider_string: FaSolidKeyboard,
    value_provider_json_object: FaSolidTruckRampBox,
    value_replacer_boolean: FaSolidWandMagicSparkles,
    value_replacer_number: FaSolidWandMagicSparkles,
    value_replacer_string: FaSolidWandMagicSparkles,
    value_replacer_json_object: FaSolidWandMagicSparkles,
    empty_list: FaSolidFile,
    list_mapping: FaSolidPersonDigging,
    value_provider_boolean: FaSolidToggleOff,
    list_set_operation: FaSolidDiagramSuccessor,
    list_sort: FaSolidArrowDownAZ,
    add_element_to_list: FaSolidList,
    optional_creation: FaSolidBoxArchive,
    empty_optional: FaSolidBoxOpen,
    list_contains: FaSolidListCheck,
    regex: FaSolidCode,
    remove_element_from_list: FaSolidBarsStaggered,
    list_distinct: FaSolidClone,
    list_reverse: FaSolidBackward,
    string_case: FaSolidArrowUpAZ,
    string_regex_replace: FaSolidTerminal,
    string_regex_split: FaSolidArrowsSplitUpAndLeft,
    ["discord.receive_command"]: FaBrandsDiscord,
    ["discord.reply_to_command"]: FaBrandsDiscord,
    ["discord.send_message"]: FaBrandsDiscord,
    ["discord.apply_role"]: FaBrandsDiscord,
    ["discord.users_with_role"]: FaBrandsDiscord,
    ["discord.receive_message"]: FaBrandsDiscord,
    ["discord.react_to_message"]: FaBrandsDiscord,
    ["discord.reply_to_message"]: FaBrandsDiscord,
    ["discord.create_embed"]: FaBrandsDiscord,
    ["discord.guild_id"]: FaBrandsDiscord,
    ["discord.channel_id"]: FaBrandsDiscord,
    ["discord.users_id"]: FaBrandsDiscord,
    ["discord.role_id"]: FaBrandsDiscord,
    ["discord.emoji_id"]: FaBrandsDiscord,
    ["discord.slash_command_event"]: FaBrandsDiscord,
    ["discord.message"]: FaBrandsDiscord,
    ["discord.message_embed"]: FaBrandsDiscord,
    get_user_data: FaSolidFileArrowDown,
    set_user_data: FaSolidFileCircleCheck,
    contains_user_data: FaSolidFileCircleQuestion,
    remove_user_data: FaSolidFileCircleXmark,
    increment_user_data: FaSolidFileCirclePlus,
    multiply_user_data: FaSolidFileExcel,
};
